# fly.toml app configuration file generated for kubecon-cloudnativecon-india-2024 on 2024-12-03T11:50:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kubecon-cloudnativecon-india-2024'

[build]

[http_service]
  internal_port = 3999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
